### ISSUE TITLE
How to retrieve the access token received from the Provider ? 

### ISSUE THREAD

**Issue by bcambel** [weavejester/ring-oauth2#14]
Hi, 

The documentation does not mention how to retrieve the access token issued by the OAuth provider. By the code I understand, it is set to the ring session, however on the landing page the `:session` of the request map does not contain any information. Is this something related to my handler setup ? I do able to see the cookie is set on the client side something like this

```ring-session=5166d573-8150-4935-afdf-f3365f6b05ed;Path=/;HttpOnly;SameSite=Lax```

An example would be very helpful. 

Thanks,
Bahadir

**Comment by weavejester** [comment]
Oh, looks like that somehow got omitted from the README. The tokens are added to the `:oauth2/access-tokens` key on the request map.

**Comment by weavejester** [comment]
Fixed in 8332cf8
