### ISSUE TITLE
Help getting started with ring-oauth2 and Luminus

### ISSUE THREAD

**Issue by perrygeo** [weavejester/ring-oauth2#17]
I'm trying to create a web server backed by github authentication using `ring-oauth2` and Luminus. Here's what I've tried:

Added middleware to wrap the `wrap-oauth2` function

```clojure
;; src/clj/project/middleware.clj
;; :require [ring.middleware.oauth2 :refer [wrap-oauth2]] 

(defn wrap-github-oauth2 [handler]
  (wrap-oauth2
   handler
   {:github
    {:authorize-uri    "https://github.com/login/oauth/authorize"
     :access-token-uri "https://github.com/login/oauth/access_token"
     :client-id        "abc"
     :client-secret    "123"
     :scopes           ["user:email"]
     :launch-uri       "/oauth2/github"
     :redirect-uri     "/oauth2/github/callback"
     :landing-uri      "/"}}))
```

then apply the middleware to my routes using the `wrap-routes` function 

```clojure
;; src/clj/project/handlers.clj

(mount/defstate app
  :start
  (middleware/wrap-base
    (routes
      (-> #'home-routes
          (wrap-routes middleware/wrap-csrf)
          (wrap-routes middleware/wrap-formats)
          (wrap-routes middleware/wrap-github-oauth2))
      (route/not-found
        (:body
          (error-page {:status 404
                       :title "page not found"}))))))
```

When I access any of the URLs for `home-routes`, I don't see any evidence that the middleware has been applied - no oauth2 redirects, no logs. I have no idea how to proceed debugging this - any advice?

**Comment by weavejester** [comment]
I've extended the README with more information on how to get the middleware working. Let me know if that answers your question.

**Comment by Yunfeng-Song** [comment]
I think you should wrap additional necessary stuff to the handlers according to the readme file. Secondly, I think you should wrap your wrap-github-oauth2 before you wrap all the necessary stuff because it seems the request is handled backwards. I created the Luminus project and made it work.
