### ISSUE TITLE
Scary error when forgetting `client_id` or `client_secret`

### ISSUE THREAD

**Issue by AndreaCrotti** [weavejester/ring-oauth2#19]
At the moment if by any chance `client_id` or `client_secret` are `nil` you would eventually get this error:

```
java.lang.IllegalArgumentException
No implementation of method: :form-encode* of protocol: #'ring.util.codec/FormEncodeable found for class: nil 
```

Which is kind of cryptic, and the thing is that since most of the times `client_id` `client_secret` would passed in (I guess) often as environment variables, it's probably easy to forget they are not set locally, and thus spending a lot of time trying to figure out what's wrong (as it happened to me). Some basic validation at least on these two fields would be enough imho.

**Comment by weavejester** [comment]
This would be a good addition. Perhaps an `assert` or precondition could be used.
