### ISSUE TITLE
Internal Server Error/404 on callback from Youtube API

### ISSUE THREAD

**Issue by ZadenRB** [weavejester/ring-oauth2#24]
My profiles for ring-oauth2 are as follows:
```
{:youtube
       {:authorize-uri "https://accounts.google.com/o/oauth2/v2/auth"
        :access-token-uri "https://accounts.google.com/o/oauth2/v2/token"
        :client-id (System/getenv "YOUTUBE_CLIENT_ID")
        :client-secret (System/getenv "YOUTUBE_CLIENT_SECRET")
        :scopes ["https://www.googleapis.com/auth/youtube"]
        :launch-uri "/auth/youtube"
        :redirect-uri "[site]/auth/youtube/callback"
        :landing-uri "/"}
       :spotify
       {:authorize-uri "https://accounts.spotify.com/authorize"
        :access-token-uri "https://accounts.spotify.com/api/token"
        :client-id (System/getenv "SPOTIFY_CLIENT_ID")
        :client-secret (System/getenv "SPOTIFY_CLIENT_SECRET")
        :launch-uri "/auth/spotify"
        :redirect-uri "[site]/auth/spotify/callback"
        :landing-uri "/"}}
```
The Spotify profile works perfectly fine, so I'm unsure what is causing the error. Navigating to the launch URI for youtube works correctly, but on the callback, the client receives a 500 Internal Server Error, and in the logs a 404 error is thrown by `cljs-http`. The full URL being redirected to is `[site]/auth/youtube/callback?state=[state]&code=[code]&scope=https://www.googleapis.com/auth/youtube`. It seems to me that the library is failing to set up the callback route, but the error isn't very descriptive, so I'm unsure. What might I be doing wrong?

**Comment by lockie** [comment]
@ZadenRB hey, have you managed to fix your problem? I'm having the same symptoms trying to add Google-based auth with Youtube scope.
