### ISSUE TITLE
Is the example `ring-defaults` missing the actual handler in README.md?

### ISSUE THREAD

**Issue by yatesco** [weavejester/ring-oauth2#32]
Hiya - I might be being dumb, but in README.md it states:
```
(wrap-defaults (-> site-defaults (assoc-in [:session :cookie-attrs :same-site] :lax)))
```

Isn't this missing the actual handler itself as the first parameter to `wrap-defaults`:
```
(wrap-defaults YOUR-ACTUAL-HANDLER (-> site-defaults (assoc-in [:session :cookie-attrs :same-site] :lax)))
```

(I realise this is probably used with `(-> YOUR-ACTUAL-HANDLER (wrap-defaults (-> ....` but it tripped me up :-))

Happy to do a PR with updated doc?

**Comment by weavejester** [comment]
Yes, that's an error, thank you for pointing that out. A PR would be welcome, though use `handler` rather than `YOUR-ACTUAL-HANDLER`.
