### ISSUE TITLE
Works when deployed to "/" but 404s when run with a context path

### ISSUE THREAD

**Issue by yatesco** [weavejester/ring-oauth2#35]
Title says it all ;-). Is this expected?

**Comment by weavejester** [comment]
I didn't get notified of this issue when you first posted it. Do you still have the problem? What do you mean by "context path"? Are running your handler as a servlet? How have you configured it? Do the internal URI options include the full path?

**Comment by yatesco** [comment]
Hi James, no worries. I've moved on and don't recall the details so let me close this and reopen it as necessary.
