### ISSUE TITLE
400 "No authorization code" on callback, even though I can see code in URL string

### ISSUE THREAD

**Issue by njerig** [weavejester/ring-oauth2#43]
I can see both code and state attached to my callback url as query params, and (when `make-redirect` is called) `get-authorization-code` returns nil. I'm not sure why this would happen, as I can see both code and state as query params in my `/callback`'s URL string.

**Comment by weavejester** [comment]
Do you have `wrap-params` in your middleware? As the README says:

> you must make sure that `ring.middleware.params/wrap-params` is enabled and runs before this middleware, as this library depends on the `:query-params key` to be present in the request.

**Comment by KaliszAd** [comment]
@njerig are you by any chance trying to setup oauth2 with Microsoft Azure? I get a very similar error and don't really know what to do.

**Comment by whatacold** [comment]
Hi, I am playing ring-oauth2 with compojure, all works well except the last step resulting in "No authorization code".

Here is `handler.clj`:
``` clojure
(ns hello-compojure.handler
  (:require [compojure.core :refer :all]
            [compojure.route :as route]
            [ring.middleware.defaults :refer [wrap-defaults site-defaults]]
            [ring.middleware.params :refer [wrap-params]]
            [ring.middleware.oauth2 :refer [wrap-oauth2]]
            [selmer.parser :refer [render render-file]]
            [selmer.util :refer [resource-path]]))

(defroutes app-routes
  (GET "/login/" [] "<a href=\"/login/github\">github</a>")
  (GET "/user/profile" request (str "whole request map:" request))
  (route/not-found "Not Found"))

;; print the request
(defn- wrap-print-request [handler]
  (fn
    ([request]
     (println "print request sync:" (:uri request) (str request))
     (handler request))
    ([request respond raise]
     (println "print request async:" (:uri request) (str request))
     (handler request respond raise))))

(def app
  (let [profiles {:github
                 {:authorize-uri    "https://github.com/login/oauth/authorize"
                  :access-token-uri "https://github.com/login/oauth/access_token"
                  :client-id        conf-client-id
                  :client-secret    conf-client-secret
                  :scopes           ["user:email"]
                  :launch-uri       "/login/github"
                  :redirect-uri     "/login/github-callback"
                  :no-auth-code-handler (fn [request] {:status 401, :headers {}, :body (str "debug no code request:" request)})
                  :landing-uri      "/user/profile"}}]
    (-> app-routes
        (wrap-defaults (assoc-in site-defaults [:session :cookie-attrs :same-site] :lax))
        wrap-params
        wrap-print-request
        (wrap-oauth2 profiles)
        )))
```

I have two questions:
1. What's wrong with the above `wrap-params`? I can confirm with a debugging `:no-auth-code-handler` that the request doesn't have `:query-params`.
2. The debugging-purpose `wrap-print-request` doesn't work with URIs `/login/github` and `/login/github-callback`, but it works with "normal" URIs like "/user/profile", why is that?

Thanks.

**Comment by whatacold** [comment]
Oops, it turns out that I place the middle-wares in wrong order, adjusting it to the below order fixes it:
```clojure
    (-> app-routes
        wrap-print-request
        (wrap-oauth2 profiles)
        (wrap-defaults (assoc-in site-defaults [:session :cookie-attrs :same-site] :lax))
        wrap-params)
```

**Comment by zikajk** [comment]
@whatacold Thank you, I have been struggling with this for an hours!
